version: '2'
services:
  app:
    image: nodeimage
    container_name: dofi_container
    build: ./
    restart: always
    ports:
    - "3030:3030"
    environment:
      - HOST=0.0.0.0
      - PORT=3030
